-- x gestire CREATE-INCOMPLETE degli ordini GasGroup
-- su next gia' portato
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('1', '18', 'CREATE-INCOMPLETE', '43', '8');
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('2', '18', 'CREATE-INCOMPLETE', '43', '8');
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('3', '18', 'CREATE-INCOMPLETE', '43', '8');
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('4', '18', 'CREATE-INCOMPLETE', '43', '8');
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('5', '18', 'CREATE-INCOMPLETE', '43', '8');
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('6', '18', 'CREATE-INCOMPLETE', '43', '8');
INSERT INTO `k_templates_orders_states_orders_actions` (`template_id`, `group_id`, `state_code`, `order_action_id`, `sort`) VALUES ('7', '18', 'CREATE-INCOMPLETE', '43', '8');

UPDATE `k_orders_actions` SET `permission` = '{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"REFERENT\",\"orderIsDes\":\"N\",\"isProdGasPromotion\":\"N\",\"isOrderTypes\": \"1,2,3,7,9\"}', `permissions` = '[{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"REFERENT\",\"orderIsDes\":\"N\",\"isProdGasPromotion\":\"N\",\"isOrderTypes\": \"1,2,3,7,9\"},{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"orderIsDes\":\"Y\",\"isTitolareDesSupplier\":\"Y\"}]' WHERE (`id` = '4');
UPDATE `k_orders_actions` SET `permission` = '{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"DES\",\"orderIsDes\":\"Y\",\"orgHasDes\":\"Y\",\"isTitolareDesSupplier\":\"N\",\"isProdGasPromotion\":\"N\",\"isOrderTypes\": \"1,2,3,7,9\"}', `permissions` = '[{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"DES\",\"orderIsDes\":\"Y\",\"orgHasDes\":\"Y\",\"isTitolareDesSupplier\":\"N\",\"isProdGasPromotion\":\"N\",\"isOrderTypes\": \"1,2,3,7,9\"},{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"DES\",\"orderIsDes\":\"N\",\"isProdGasPromotion\":\"N\"}]' WHERE (`id` = '7');
UPDATE `k_orders_actions` SET `permission` = '{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"SUPPLIER\",\"orderIsDes\":\"Y\",\"orgHasDes\":\"Y\",\"isTitolareDesSupplier\":\"Y\",\"isOrderTypes\": \"1,2,3,7,9\"}', `permissions` = '[{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"SUPPLIER\",\"orderIsDes\":\"Y\",\"orgHasDes\":\"Y\",\"isTitolareDesSupplier\":\"Y\",\"isOrderTypes\": \"1,2,3,7,9\"},{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"articlesOwner\":\"SUPPLIER\",\"orderIsDes\":\"N\",\"isProdGasPromotion\":\"N\"}]' WHERE (`id` = '36');
UPDATE `k_orders_actions` SET `permissions` = '[{\"orgHasArticlesOrder\":\"Y\",\"userHasArticlesOrder\":\"Y\",\"isOrderTypes\": \"10,11\"}]' WHERE (`id` = '43');
